#!/usr/bin/env bash

if [ "$1" == "start" ]; then
    sudo docker-compose start
fi

if [ "$1" == "stop" ]; then
    sudo docker-compose stop
fi

if [ "$1" == "update" ]; then    
    sudo docker-compose pull && sudo docker-compose up -d && sudo docker image prune -f
fi

if [ "$1" == "setup" ]; then
  echo 'Setting system...' \
  && rm -rf ghost; git clone https://github.com/dhairya137/ghost-auto ghost \
  && cd ghost \
  && sed -i "s/<domain>/$2/g" docker-compose.yml \
  && sed -i "s/<domain>/$2/g" docker-compose.production.yml \
  && sed -i "s/<email>/$3/g" docker-compose.yml \
  && sed -i "s/<domain>/$2/g" nginx/default.conf \
  echo 'Installing SSL...' \
  && sudo docker-compose up \
  && echo 'Preparing docker-compose up' \
  && sudo docker-compose down -v \
  && mv docker-compose.yml docker-compose.ssl.yml \
  && mv docker-compose.production.yml docker-compose.yml \
  && echo 'Preparing Ghost...' \
  && mkdir ./content; sudo mkdir -p /usr/share/nginx/html; \
  echo 'Configuring cron...' \
  && echo "0 23 * * * docker start certbot >> /var/log/docker_cron.log 2>&1
  5 23 * * * docker exec nginx nginx -s reload >> /var/log/docker_cron.log 2>&1" >> mycron \
  && sudo crontab mycron; rm mycron \
  && sudo chmod +x dcsimple \
  && echo 'Starting Docker db...' \
  && sudo docker-compose up -d db \
  && echo 'Waiting 10 secs for mysqldb to build databases...' \
  && sleep 10 \
  && sudo docker-compose up -d --no-deps ghost \
  && echo 'Waiting 20 secs for Ghost to install ghost files...' \
  && sleep 20 \
  && echo 'Now starting Nginx!' \
  && sudo docker-compose up -d --no-deps nginx \
  && echo 'Done! 🎉' \
  && echo 'by Rafael Correa Gomes and Woosung Choi' \
  && echo 'Access your ghost: https://'$2;
  echo 'Access your ghost admin page: https://'$2'/ghost';
fi
